name: over_react_bootstrap
version: 0.0.1
description: Bootstrap UI components built with OverReact
homepage: https://github.com/alademann/over_react_bootstrap/
authors:
  - Aaron Lademann <aaron.lademann@gmail.com>
environment:
  sdk: ^2.4.0

dependencies:
  over_react: ^2.0.0

dev_dependencies:
  build_runner: ^1.6.3
  build_web_compilers: ^2.0.0
  dart_dev: ^2.1.0
  dependency_validator: ^1.0.0
  over_react_test: ^2.0.0
  test: any
