name: over_react_bootstrap
version: 0.0.1
description: Bootstrap UI components built with OverReact
homepage: https://github.com/alademann/over_react_bootstrap/
authors:
  - Aaron Lademann <aaron.lademann@gmail.com>
environment:
  sdk: ">=1.24.2"
dependencies:
  bootstrap: ^4.0.0
  over_react: ^1.20.0
dev_dependencies:
  coverage: ^0.7.2
  dart_dev: ^1.7.6
  dependency_validator: ^1.0.0
  over_react_test: ^1.2.0
  test: ^0.12.24
transformers:
  - bootstrap:
      url: //maxcdn.bootstrapcdn.com/bootstrap/{{version}}
      version: 4.0.0
  - over_react:
      # Apply workaround for https://github.com/dart-lang/sdk/issues/29914
      fixDdcAbstractAccessors: true
  - test/pub_serve:
      $include: test/**_test{.*,}.dart

dependency_overrides:
  # Workaround until 4.0.0 is released to pub (https://github.com/richerlariviere/bootstrap_for_pub/pull/30)
  bootstrap:
    git:
      url: git@github.com:alademann/bootstrap_for_pub.git
      ref: bs_4.0.0
